export const SET_INVOICE_CLIENT = "SET_INVOICE_CLIENT"
export const PUSH_EQUIPMENT = "PUSH_EQUIPMENT"
export const DELETE_EQUIPMENT = "DELETE_EQUIPMENT" 
export const CREATE_INVOICE = 'CREATE_INVOICE'
export const RESET_INVOICE = 'RESET_INVOICE'
export const GET_INVOICES = 'GET_INVOICES'